In [2]:
import random
import time
import pandas as pd

#구글 드라이브와 연동
from google.colab import drive
drive.mount('/content/gdrive')
directory_path = '/content/gdrive/My Drive/Colab Notebooks/'

data = pd.read_csv(directory_path+'list.csv', encoding = 'UTF-8')
count = int(input('팀 개수를 입력하세요 : '))
mem = int(input('팀 인원을 입력하세요 : '))
grade1 = []
grade2 = []

pd.set_option('mode.chained_assignment',  None)

for i in range(len(data.index)):
    if data['grade'][i] == 1:
        grade1.append(i)
    else:
        grade2.append(i)


data['teams'] = 0

random.shuffle(grade1)
random.shuffle(grade2)

for i in range(count):
    data['teams'][grade1[i]] = i+1
    data['teams'][grade2[i]] = i+1

remain = data[data['teams'] == 0].index.tolist()
i = 0

while len(data[data['teams'] == 0]) != 0:
    num = random.randint(1, count)
    if len(data[data['teams'] == num]) == mem:
        continue
    else:
        data['teams'][remain[i]] = num
        i +=1

for team, group in data.groupby('teams')['name']:
    names = ', '.join(group)
    print(f"팀 {team} : ({names})")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
팀 개수를 입력하세요 : 10
팀 인원을 입력하세요 : 2
팀 1 : (송윤주, 이다은)
팀 2 : (신지현, 한채빈)
팀 3 : (윤주연, 최재혁)
팀 4 : (김영욱, 박지영)
팀 5 : (이창영, 장유정)
팀 6 : (장다은, 정현주)
팀 7 : (안수연, 오세영)
팀 8 : (권창범, 이지원)
팀 9 : (김지현, 오윤주)
팀 10 : (송한나, 정혜수)